---
name: "Npm Linters"

on: push

jobs:
  "Prettier":
    runs-on: ubuntu-latest
    container: node:20

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Check Prettier formatting
        run: npm run lint
